export const schemas = {
  conditions: {
    title: 'Conditions',
    description: 'Diagnosed conditions, ongoing or past.',
    fields: [
      { key: 'name', label: 'Condition', type: 'text', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'chronic', 'resolved'] },
      { key: 'diagnosed_date', label: 'Diagnosed date', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    primary: 'name',
    secondary: (r) => [r.status, r.diagnosed_date].filter(Boolean).join(' · '),
  },
  medications: {
    title: 'Medications',
    description: 'Current and past prescriptions.',
    fields: [
      { key: 'name', label: 'Medication', type: 'text', required: true },
      { key: 'dosage', label: 'Dosage', type: 'text' },
      { key: 'frequency', label: 'Frequency', type: 'text' },
      { key: 'prescribing_doctor', label: 'Prescribing doctor', type: 'text' },
      { key: 'start_date', label: 'Start date', type: 'date' },
      { key: 'end_date', label: 'End date', type: 'date' },
      { key: 'is_active', label: 'Currently taking', type: 'checkbox' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    primary: 'name',
    secondary: (r) => [r.dosage, r.frequency].filter(Boolean).join(' · '),
  },
  allergies: {
    title: 'Allergies',
    description: 'Allergies and adverse reactions.',
    fields: [
      { key: 'allergen', label: 'Allergen', type: 'text', required: true },
      { key: 'reaction', label: 'Reaction', type: 'text' },
      { key: 'severity', label: 'Severity', type: 'select', options: ['mild', 'moderate', 'severe'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    primary: 'allergen',
    secondary: (r) => [r.severity, r.reaction].filter(Boolean).join(' · '),
  },
  immunizations: {
    title: 'Immunizations',
    description: 'Vaccines and dates given.',
    fields: [
      { key: 'vaccine', label: 'Vaccine', type: 'text', required: true },
      { key: 'date_given', label: 'Date given', type: 'date' },
      { key: 'provider', label: 'Provider', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    primary: 'vaccine',
    secondary: (r) => [r.date_given, r.provider].filter(Boolean).join(' · '),
  },
  labs: {
    title: 'Lab Results',
    description: 'Bloodwork and other test results.',
    fields: [
      { key: 'test_name', label: 'Test name', type: 'text', required: true },
      { key: 'test_date', label: 'Test date', type: 'date' },
      { key: 'result_value', label: 'Result', type: 'text' },
      { key: 'unit', label: 'Unit', type: 'text' },
      { key: 'reference_range', label: 'Reference range', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    primary: 'test_name',
    secondary: (r) => [r.result_value && `${r.result_value}${r.unit ? ' ' + r.unit : ''}`, r.test_date].filter(Boolean).join(' · '),
  },
  visits: {
    title: 'Doctor Visits',
    description: 'Appointment notes and summaries.',
    fields: [
      { key: 'visit_date', label: 'Visit date', type: 'date', required: true },
      { key: 'provider', label: 'Provider', type: 'text' },
      { key: 'reason', label: 'Reason', type: 'text' },
      { key: 'summary', label: 'Summary', type: 'textarea' },
    ],
    primary: (r) => r.reason || r.provider || r.visit_date,
    secondary: (r) => [r.provider, r.visit_date].filter(Boolean).join(' · '),
  },
  contacts: {
    title: 'Emergency & Care Contacts',
    description: 'Doctors, family, and emergency contacts.',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'relationship', label: 'Relationship', type: 'text' },
      { key: 'role', label: 'Role (e.g. cardiologist, spouse)', type: 'text' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    primary: 'name',
    secondary: (r) => [r.role, r.phone].filter(Boolean).join(' · '),
  },
};
